// --- KEYBOARD COMPONENTS ---
const KEYBOARD_LAYOUTS = {
  qwerty: [
    [
      { k: "1" },
      { k: "2" },
      { k: "3" },
      { k: "4" },
      { k: "5" },
      { k: "6" },
      { k: "7" },
      { k: "8" },
      { k: "9" },
      { k: "0" },
    ],
    [
      { k: "Q" },
      { k: "W" },
      { k: "E" },
      { k: "R" },
      { k: "T" },
      { k: "Y" },
      { k: "U" },
      { k: "I" },
      { k: "O" },
      { k: "P" },
    ],
    [
      { k: "A" },
      { k: "S" },
      { k: "D" },
      { k: "F" },
      { k: "G" },
      { k: "H" },
      { k: "J" },
      { k: "K" },
      { k: "L" },
      { k: "DEL", span: 1 },
    ],
    [
      { k: "Z" },
      { k: "X" },
      { k: "C" },
      { k: "V" },
      { k: "B" },
      { k: "N" },
      { k: "M" },
      { k: "SPACE", span: 2 },
      { k: "ENTER", span: 1 },
    ],
  ],
  azerty: [
    [
      { k: "1" },
      { k: "2" },
      { k: "3" },
      { k: "4" },
      { k: "5" },
      { k: "6" },
      { k: "7" },
      { k: "8" },
      { k: "9" },
      { k: "0" },
    ],
    [
      { k: "A" },
      { k: "Z" },
      { k: "E" },
      { k: "R" },
      { k: "T" },
      { k: "Y" },
      { k: "U" },
      { k: "I" },
      { k: "O" },
      { k: "P" },
    ],
    [
      { k: "Q" },
      { k: "S" },
      { k: "D" },
      { k: "F" },
      { k: "G" },
      { k: "H" },
      { k: "J" },
      { k: "K" },
      { k: "L" },
      { k: "M" },
    ],
    [
      { k: "W" },
      { k: "X" },
      { k: "C" },
      { k: "V" },
      { k: "B" },
      { k: "N" },
      { k: "SPACE", span: 2 },
      { k: "DEL", span: 1 },
      { k: "ENTER", span: 1 },
    ],
  ],
};

export { KEYBOARD_LAYOUTS };
